name: test-and-lint

on: push

env:
  CI: true

jobs: 

  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps: 
      - uses: actions/checkout@v2

      - name: tests and eslint run
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
      - run: make install
      
      - name: test and lint
      - run: make lint
      - run: make test

      - name: test-coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
